<?php
/**
 * Centralised default content for all editable fields.
 *
 * Both the templates (via pl_meta) and the meta box form (via pl_field) read
 * defaults from here, so the site renders correctly even before any page has
 * been saved in the admin, AND the meta box always shows the matching value
 * as a placeholder.
 */
defined('ABSPATH') || exit;

function pl_defaults_map(): array {
    static $map = null;
    if ($map !== null) return $map;

    $map = [

        /* ──────────── FRONT PAGE ──────────── */
        'pl_home_hero_title1'    => 'Norges største',
        'pl_home_hero_title2'    => 'på montering og vedlikehold',
        'pl_home_hero_desc'      => 'Montering, service og vedlikehold av stålhaller, plasthaller og dukhaller.',
        'pl_home_hero_btn1_text' => 'VÅRE TJENESTER',
        'pl_home_hero_btn1_link' => '/tjenester',
        'pl_home_hero_btn2_text' => 'RING 70 00 86 04',
        'pl_home_hero_btn2_link' => 'tel:+4770008604',

        'pl_home_services_title' => 'Vi tilbyr',
        'pl_home_services_intro' => 'Montering, demontering, flytting og vedlikehold av duk- og stålhaller',

        'pl_home_card1_title' => 'Montering',
        'pl_home_card1_desc'  => 'Trenger du å montere eller demontere en hall? Vi utfører montering og demontering på alle typer dukhaller og stålhaller over hele landet.',
        'pl_home_card1_link'  => '/montering',
        'pl_home_card2_title' => 'Tjenester',
        'pl_home_card2_desc'  => 'Montering, demontering, flytting og vedlikehold av alle typer haller – inkludert dukskift, isolering og reparasjon av skader. Serviceavtale sikrer forutsigbar drift og reduserer risiko for driftsstans.',
        'pl_home_card2_link'  => '/tjenester',
        'pl_home_card3_title' => 'Vedlikehold',
        'pl_home_card3_desc'  => 'Regelmessig vedlikehold er nøkkelen til lang levetid og trygg drift av din hall. Våre serviceavtaler gir deg trygghet og forutsigbare kostnader.',
        'pl_home_card3_link'  => '/vedlikehold',

        'pl_home_stat1_num'   => '1681',
        'pl_home_stat1_label' => 'Monterte dukhaller',
        'pl_home_stat2_num'   => '200',
        'pl_home_stat2_label' => 'Stålbygg montert',
        'pl_home_stat3_num'   => '20796',
        'pl_home_stat3_label' => 'Servicer utført',
        'pl_home_stat4_num'   => '375',
        'pl_home_stat4_label' => 'Dukhaller flyttet',

        'pl_home_cta_title' => 'Klar for å starte ditt prosjekt?',
        'pl_home_cta_intro' => 'Kontakt oss i dag for en uforpliktende samtale om dine behov',

        /* ──────────── TJENESTER ──────────── */
        'pl_tj_hero_title1' => 'Våre',
        'pl_tj_hero_title2' => 'tjenester',
        'pl_tj_hero_desc'   => 'Komplett service for montering, vedlikehold og flytting av haller.',

        'pl_tj_card1_title' => 'Montering og demontering',
        'pl_tj_card1_desc'  => 'Plamek monterer, demonterer og flytter alle typer duk- og stålhaller.',
        'pl_tj_card1_link'  => '/montering',
        'pl_tj_card2_title' => 'Flytting av hall',
        'pl_tj_card2_desc'  => 'Vi flytter alle typer haller i hele landet!',
        'pl_tj_card2_link'  => '/flytting-av-hall',
        'pl_tj_card3_title' => 'Serviceavtale / vedlikehold',
        'pl_tj_card3_desc'  => 'En serviceavtale med Plamek AS reduserer risikoen for uforutsette kostnader og driftsstans i bygget.',
        'pl_tj_card3_link'  => '/vedlikehold',
        'pl_tj_card4_title' => 'Dukskift og isolering av hall',
        'pl_tj_card4_desc'  => 'Har bygningen behov for skift av duk?',
        'pl_tj_card4_link'  => '/dukskift-isolering',
        'pl_tj_card5_title' => 'Reparering av skader på hall',
        'pl_tj_card5_desc'  => 'Har hallen din fått en skade? Vi reparerer alle slags skader på dukhaller.',
        'pl_tj_card5_link'  => '/reparering-av-skader',
        'pl_tj_card6_title' => 'Kontakt!',
        'pl_tj_card6_desc'  => 'Har du spørsmål om våre tjenester eller ønsker et tilbud?',
        'pl_tj_card6_link'  => '/kontakt',

        'pl_tj_benefits_title' => 'Hvorfor velge Plamek?',
        'pl_tj_benefits_intro' => 'Med over 30 års erfaring er vi en pålitelig partner for alle dine industrielle monteringsprosjekter',
        'pl_tj_benefit1_title' => '30+ års erfaring',
        'pl_tj_benefit1_desc'  => 'Lang erfaring med alle typer monteringsprosjekter gir oss kompetanse til å løse de mest utfordrende oppdragene.',
        'pl_tj_benefit2_title' => 'Høy kvalitet',
        'pl_tj_benefit2_desc'  => 'Vi setter kvalitet i høysetet og bruker kun materialer og metoder som sikrer lang levetid og pålitelighet.',
        'pl_tj_benefit3_title' => 'HMS-fokus',
        'pl_tj_benefit3_desc'  => 'Sikkerhet kommer først. All vårt personell er HMS-sertifisert og følger strenge sikkerhetsprosedyrer.',
        'pl_tj_benefit4_title' => 'Pålitelige leveranser',
        'pl_tj_benefit4_desc'  => 'Vi holder avtaler og frister. Våre kunder kan stole på at prosjektet blir ferdig til avtalt tid.',
        'pl_tj_benefit5_title' => 'Landsdekking',
        'pl_tj_benefit5_desc'  => 'Vi utfører oppdrag over hele Norge og har erfaring med prosjekter i alle typer værforhold.',
        'pl_tj_benefit6_title' => 'Komplett tjeneste',
        'pl_tj_benefit6_desc'  => 'Fra planlegging til ferdigstillelse tilbyr vi en komplett tjeneste som dekker alle aspekter av prosjektet.',

        'pl_tj_cta_title'    => 'Klar for å starte prosjektet?',
        'pl_tj_cta_text'     => 'Ta kontakt for en uforpliktende prat om dine behov.',
        'pl_tj_cta_btn_text' => 'Kontakt oss',

        /* ──────────── MONTERING ──────────── */
        'pl_mont_hero_title1' => 'Montering og',
        'pl_mont_hero_title2' => 'demontering',
        'pl_mont_hero_desc'   => 'Trenger du å montere eller demontere en hall? Vi utfører montering og demontering på alle typer dukhaller og stålhaller over hele landet.',
        'pl_mont_hero_tag'    => 'Ledende spesialist innen design, produksjon og konstruksjon.',

        'pl_mont_intro_title' => 'Rask montering og demontering av plasthaller og stålbygg',
        'pl_mont_intro_p1'    => 'Vi hjelper deg med montering av ditt bygg raskt og effektivt. Vi jobber med både plasthaller og stålbygg. Plamek har over 40 års erfaring i bransjen, og med dyktige og erfarne fagfolk håndterer vi alle typer byggeprosjekter, fra enkle konstruksjoner til de mest komplekse prosjektene.',
        'pl_mont_intro_p2'    => 'Vi setter opp hallen din der du måtte ønske, uavhengig om det er en dukhall eller stålhall.',

        'pl_mont_card1_title' => 'Montering plasthall',
        'pl_mont_card1_sub'   => 'Vi monterer din hall – trygt og effektivt',
        'pl_mont_card1_desc'  => 'Hos oss kan du være trygg på at monteringsjobben utføres på en sikker og god måte.',
        'pl_mont_card1_ext'   => 'Alle våre ansatte har sertifikater og kurs som ivaretar kvalitet og sikkerhet på byggeplassen. Trygge og faglig dyktige medarbeider er viktig for å ivareta kvaliteten du som kunde fortjener. Slik at du slipper å tenke på bygget, og heller fokusere på bedriftens kjernevirksomhet.',
        'pl_mont_card1_b1'    => 'Sertifiserte og erfarne fagfolk',
        'pl_mont_card1_b2'    => 'Fokus på sikkerhet og kvalitet',
        'pl_mont_card1_b3'    => 'Trygg og effektiv utførelse',

        'pl_mont_card2_title' => 'Demontering av hall',
        'pl_mont_card2_desc'  => 'Har du behov for å demontere en hall? Vi tar oppdrag for demontering av haller over hele landet. Vi tilbyr også flytting av hall.',
        'pl_mont_card2_ext'   => 'Kontakt oss i dag for et uforpliktende tilbud for montering eller demontering av din hall!',
        'pl_mont_card2_b1'    => 'Demontering over hele landet',
        'pl_mont_card2_b2'    => 'Flytting av eksisterende haller',
        'pl_mont_card2_b3'    => 'Uforpliktende tilbud',

        'pl_mont_st_title' => 'Montering stålbygg',
        'pl_mont_st_desc'  => 'Vi har omfattende erfaring med montering av stålbygg og stålkonstruksjoner. Fra enkle konstruksjoner til komplekse industriprosjekter.',

        'pl_mont_ct_title' => 'Kontakt oss for et uforpliktende tilbud',
        'pl_mont_ct_desc'  => 'Trenger du montering eller demontering av hall? Vi gir deg et konkurransedyktig tilbud basert på dine behov.',

        /* ──────────── VEDLIKEHOLD ──────────── */
        'pl_ved_hero_title1' => 'Serviceavtale og',
        'pl_ved_hero_title2' => 'vedlikehold',
        'pl_ved_hero_desc'   => 'En serviceavtale med Plamek AS reduserer risikoen for uforutsette kostnader og driftsstans i bygget. Vi tilbyr skreddersydde avtaler for alle typer haller.',
        'pl_ved_off_title'   => 'Hva inngår i en serviceavtale?',
        'pl_ved_off_intro'   => 'Vi skreddersyr avtalen etter deres behov, men typiske elementer inkluderer:',
        'pl_ved_off1_title'  => 'Dukskift',
        'pl_ved_off1_desc'   => 'Hele eller oppussing av eksisterende duk',
        'pl_ved_off2_title'  => 'Isolerte løsninger',
        'pl_ved_off2_desc'   => 'Profesjonell isolering av eksisterende haller',
        'pl_ved_off3_title'  => 'Lysoppgraderinger',
        'pl_ved_off3_desc'   => 'LED og grønnere belysningsløsninger',
        'pl_ved_off4_title'  => 'Dør- og inngangssystemer',
        'pl_ved_off4_desc'   => 'Avanserte dør- og inngangssystemer',
        'pl_ved_off5_title'  => 'Skilting på bygning',
        'pl_ved_off5_desc'   => 'Profesjonell skilting og merking',
        'pl_ved_off6_title'  => 'VVS / klimakontroll',
        'pl_ved_off6_desc'   => 'Ventilasjon, varme og avfukting',
        'pl_ved_ben_title'   => 'Fordeler med jevnlig vedlikehold',
        'pl_ved_ben1_title'  => 'Rask utførelse',
        'pl_ved_ben1_desc'   => 'Jobben utføres raskt og effektivt',
        'pl_ved_ben2_title'  => 'Fleksible løsninger',
        'pl_ved_ben2_desc'   => 'Hele eller deler av duken - akkurat det du trenger',
        'pl_ved_ben3_title'  => 'Landsdekkende',
        'pl_ved_ben3_desc'   => 'Vi kommer der hallen er, uansett hvor i landet',
        'pl_ved_ben4_title'  => 'Komplett service',
        'pl_ved_ben4_desc'   => 'Fra dukskift til isolering og oppgraderinger',
        'pl_ved_g1_title'    => 'Ridehall før dukskift',
        'pl_ved_g1_desc'     => 'Gammel og slitt duk som trenger utskifting',
        'pl_ved_g2_title'    => 'Ridehall med ny duk',
        'pl_ved_g2_desc'     => 'Ferdig oppgradert hall med ny duk fra Plamek',
        'pl_ved_cta_btn'     => 'Bestill service',

        /* ──────────── DUKSKIFT OG ISOLERING ──────────── */
        'pl_duk_hero_title1' => 'Dukskift og',
        'pl_duk_hero_title2' => 'isolering av hall',
        'pl_duk_hero_desc'   => 'Har bygningen behov for skift av duk? Eller ønsker du å etterisolere din eksisterende hall? Vi hjelper deg med å fornye og oppgradere hallen din.',
        'pl_duk_off_title'   => 'Vi utfører følgende tjenester',
        'pl_duk_off_intro'   => 'Profesjonell oppgradering og vedlikehold av din hall.',
        'pl_duk_off1_title'  => 'Dukskift',
        'pl_duk_off1_desc'   => 'Hele eller oppussing av eksisterende duk',
        'pl_duk_off2_title'  => 'Isolerte løsninger',
        'pl_duk_off2_desc'   => 'Profesjonell isolering av eksisterende haller',
        'pl_duk_off3_title'  => 'Lysoppgraderinger',
        'pl_duk_off3_desc'   => 'LED og grønnere belysningsløsninger',
        'pl_duk_off4_title'  => 'Dør- og inngangssystemer',
        'pl_duk_off4_desc'   => 'Avanserte dør- og inngangssystemer',
        'pl_duk_off5_title'  => 'Skilting på bygning',
        'pl_duk_off5_desc'   => 'Profesjonell skilting og merking',
        'pl_duk_off6_title'  => 'VVS / klimakontroll',
        'pl_duk_off6_desc'   => 'Ventilasjon, varme og avfukting',
        'pl_duk_ben_title'   => 'Hvorfor oppgradere hallen?',
        'pl_duk_ben1_title'  => 'Rask utførelse',
        'pl_duk_ben1_desc'   => 'Jobben utføres raskt og effektivt',
        'pl_duk_ben2_title'  => 'Fleksible løsninger',
        'pl_duk_ben2_desc'   => 'Hele eller deler av duken - akkurat det du trenger',
        'pl_duk_ben3_title'  => 'Landsdekkende',
        'pl_duk_ben3_desc'   => 'Vi kommer der hallen er, uansett hvor i landet',
        'pl_duk_ben4_title'  => 'Komplett service',
        'pl_duk_ben4_desc'   => 'Fra dukskift til isolering og oppgraderinger',
        'pl_duk_g1_title'    => 'Hall før dukskift',
        'pl_duk_g1_desc'     => 'Gammel og slitt duk som trenger utskifting',
        'pl_duk_g2_title'    => 'Hall med ny duk',
        'pl_duk_g2_desc'     => 'Ferdig oppgradert hall med ny duk fra Plamek',
        'pl_duk_cta_btn'     => 'Be om befaring',

        /* ──────────── FLYTTING AV HALL ──────────── */
        'pl_fly_hero_title1' => 'Flytting av',
        'pl_fly_hero_title2' => 'hall',
        'pl_fly_hero_desc'   => 'Profesjonell demontering, transport og ny montering av haller.',
        'pl_fly_intro_title' => 'Komplett hallflytting',
        'pl_fly_intro_p1'    => 'Plamek har lang erfaring med å flytte haller fra en lokasjon til en annen. Vi håndterer alt fra demontering på opprinnelig sted til montering på ny lokasjon. Vårt team sørger for at hele prosessen går smidig og effektivt.',
        'pl_fly_intro_p2'    => 'Vi tar hånd om hele prosessen - fra planlegging og demontering til transport og montering på nytt sted. Vårt erfarne team sørger for at hallen din kommer trygt frem. Flytting av hall kan gjøres både med hel-løft og demontering/remontering.',
        'pl_fly_intro_p3'    => 'Alle komponenter merkes og dokumenteres for å sikre korrekt gjenmontering. Vi arbeider nøye og systematisk for å bevare hallens integritet gjennom hele flytteprosessen. Sikkerhet er viktig for oss. Alle våre ansatte har sertifikater og kurs som ivaretar kvalitet og sikkerhet på byggeplassen.',
        'pl_fly_intro_p4'    => 'Dette gjør at du som kunde kan være trygg på at jobben vi gjør blir gjennomført av et team med god kunnskap og lang erfaring.',
        'pl_fly_intro_cta'   => 'Ta kontakt for mer informasjon om hvordan vi kan flytte hallen din – sikkert og smidig!',
        'pl_fly_proc_title'  => 'Fra A til Å',
        'pl_fly_proc_intro'  => 'Vår flytteprosess inkluderer:',
        'pl_fly_proc1_title' => 'Stedsinspeksjon',
        'pl_fly_proc1_desc'  => 'Grundig inspeksjon av både gammelt og nytt sted',
        'pl_fly_proc2_title' => 'Profesjonell demontering',
        'pl_fly_proc2_desc'  => 'Systematisk nedtaking med merking av alle komponenter',
        'pl_fly_proc3_title' => 'Sikker transport',
        'pl_fly_proc3_desc'  => 'Transportløsninger tilpasset hallens størrelse og komponenter',
        'pl_fly_proc4_title' => 'Grunnarbeid',
        'pl_fly_proc4_desc'  => 'Klargjøring av fundament på ny lokasjon',
        'pl_fly_proc5_title' => 'Gjenmontering',
        'pl_fly_proc5_desc'  => 'Komplett montering på nytt sted med kvalitetskontroll',
        'pl_fly_proc6_title' => 'Garanti og oppfølging',
        'pl_fly_proc6_desc'  => 'Garanti på arbeidet og oppfølging etter ferdigstillelse',
        'pl_fly_ben_title'   => 'Fordeler med profesjonell hallflytting',
        'pl_fly_ben1_title'  => 'Effektiv prosess',
        'pl_fly_ben1_desc'   => 'Planlagt og strukturert tilnærming for rask gjennomføring',
        'pl_fly_ben2_title'  => 'Trygg håndtering',
        'pl_fly_ben2_desc'   => 'Erfarne teknikere som ivaretar hallens kvalitet',
        'pl_fly_ben3_title'  => 'Komplett service',
        'pl_fly_ben3_desc'   => 'Alt fra demontering til ferdig montering på nytt sted',
        'pl_fly_ben4_title'  => 'Kvalitetsgaranti',
        'pl_fly_ben4_desc'   => 'Garanti på arbeidet og oppfølging etter ferdigstillelse',
        'pl_fly_g1_title'    => 'Før flytting',
        'pl_fly_g1_desc'     => 'Hall klar for demontering på opprinnelig lokasjon',
        'pl_fly_g2_title'    => 'Etter flytting',
        'pl_fly_g2_desc'     => 'Hall ferdig montert på ny lokasjon',
        'pl_fly_cta_btn'     => 'Be om tilbud',

        /* ──────────── REPARERING AV SKADER ──────────── */
        'pl_rep_hero_title1' => 'Reparering av',
        'pl_rep_hero_title2' => 'skader på hall',
        'pl_rep_hero_desc'   => 'Profesjonell reparasjon og utbedring av skader på alle typer haller',
        'pl_rep_overview_title' => 'Ekspertise innen skadesreparasjon',
        'pl_rep_overview_desc'  => 'Plamek har omfattende erfaring med å reparere alle typer skader på haller. Fra mindre utbedringer til store reparasjonsprosjekter - vi har løsningen. Vårt team diagnostiserer skaden og utfører nødvendige reparasjoner for å gjenopprette hallens funksjonalitet og sikkerhet.',
        'pl_rep_dt_title'    => 'Vi reparerer blant annet:',
        'pl_rep_dt_intro'    => 'Uansett skadeomfang har vi kompetansen til å utbedre det.',
        'pl_rep_proc_title'  => 'Fra diagnose til ferdig reparasjon',
        'pl_rep_proc_p1'     => 'Vi starter med en grundig inspeksjon for å identifisere årsaken til skaden og omfanget av reparasjonsarbeidet. Deretter utarbeider vi en detaljert plan for utbedringen.',
        'pl_rep_proc_p2'     => 'Alle reparasjoner utføres med originale eller likeverdige komponenter for å sikre at hallen opprettholder sin opprinnelige kvalitet og funksjonalitet.',
        'pl_rep_dt1_title'   => 'Dukskader',
        'pl_rep_dt1_desc'    => 'Rifter, hull og slitasje på hallduken',
        'pl_rep_dt2_title'   => 'Konstruksjonsskader',
        'pl_rep_dt2_desc'    => 'Skader på rammeverk og bærende konstruksjoner',
        'pl_rep_dt3_title'   => 'Dør- og portskader',
        'pl_rep_dt3_desc'    => 'Reparasjon av innganger og portløsninger',
        'pl_rep_dt4_title'   => 'Værskader',
        'pl_rep_dt4_desc'    => 'Utbedring etter storm, snølast og haglskader',
        'pl_rep_dt5_title'   => 'Isolasjonsskader',
        'pl_rep_dt5_desc'    => 'Reparasjon og utskifting av isolasjonsmaterialer',
        'pl_rep_dt6_title'   => 'Ventilasjonsskader',
        'pl_rep_dt6_desc'    => 'Reparasjon av ventilasjons- og klimasystemer',
        'pl_rep_ben_title'   => 'Fordeler med profesjonell skadesreparasjon',
        'pl_rep_ben1_title'  => 'Rask respons',
        'pl_rep_ben1_desc'   => 'Hurtig utrykning ved akutte skader',
        'pl_rep_ben2_title'  => 'Ekspertise',
        'pl_rep_ben2_desc'   => 'Spesialisert kunnskap om alle halltyper',
        'pl_rep_ben3_title'  => 'Kvalitetsgaranti',
        'pl_rep_ben3_desc'   => 'Garanti på alle reparasjoner vi utfører',
        'pl_rep_ben4_title'  => 'Originale deler',
        'pl_rep_ben4_desc'   => 'Bruker originale eller likeverdige komponenter',
        'pl_rep_g1_title'    => 'Før reparasjon',
        'pl_rep_g1_desc'     => 'Hall med skader som må utbedres',
        'pl_rep_g2_title'    => 'Etter reparasjon',
        'pl_rep_g2_desc'     => 'Hall i perfekt stand etter profesjonell reparasjon',
        'pl_rep_cta_btn'     => 'Meld skade',

        /* ──────────── OM PLAMEK ──────────── */
        'pl_om_hero_title1' => 'Om',
        'pl_om_hero_title2' => 'Plamek AS',
        'pl_om_hero_desc'   => 'Bygg, service, vedlikehold og ettermarkedsløsninger for en lang rekke markedssektorer.',

        // About section ("Hvem er vi?")
        'pl_om_about_title'    => 'Hvem er',
        'pl_om_about_subtitle' => 'vi?',
        'pl_om_about_p1'       => 'Plamek har over 30 års erfaring i bransjen. Med dyktige og erfarne fagfolk håndterer vi de aller fleste byggeprosjekter.',
        'pl_om_about_p2'       => 'Vi tilbyr et bredt spekter av bygge- og monteringstjenester. I tillegg bistår vi byggherrer og forsikringsselskap i skadesaker på bygg.',
        'pl_om_about_p3'       => 'Her kan vi bistå med takst, enkle verdivurderinger og reparasjon av skaden.',

        // Services section ("Montering, demontering og flytting av haller")
        'pl_om_serv_title'    => 'Montering, demontering og',
        'pl_om_serv_subtitle' => 'flytting av haller',
        'pl_om_serv_p1'       => 'Plamek monterer, demonterer og flytter alle typer duk- og stålhaller. Vi tilbyr også reparasjon og vedlikehold av bygninger.',
        'pl_om_serv_p2'       => 'Vi utfører service på alle typer haller i hele landet, og tilbyr egne serviceavtaler.',

        // Quality / Safety / Workplace
        'pl_om_quality_title'    => 'Kvalitet og',
        'pl_om_quality_subtitle' => 'sikkerhet',
        'pl_om_safety_title'     => 'Sikkerhet i fokus',
        'pl_om_safety_p1'        => 'Plamek har stort fokus på kvalitet og sikkerhet i arbeid. Vi har et bredt spekter av kurs for å dekke vårt arbeidsfelt, og personlig sikkerhet er meget viktig.',
        'pl_om_safety_p2'        => 'I tillegg er re-sertifisering på arbeidsutstyr og løfteverktøy satt i system slik at risikoen for ulykker reduseres.',
        'pl_om_workplace_title'  => 'Gode arbeidsplasser',
        'pl_om_workplace_p1'     => 'Som arbeidsgiver er vi opptatt av trygge og gode arbeidsplasser. I samarbeid med bedriftshelsetjenesten blir arbeidsforholdene på byggeplassen kartlagt, psykoanalyser gjennomført, og eventuelle tiltak blir iverksatt.',
        'pl_om_workplace_p2'     => 'Trygge og faglig dyktige medarbeider er viktig for å ivareta kvaliteten du som kunde fortjener. Slik at du slipper å tenke på bygget, og heller fokusere på bedriftens kjernevirksomhet.',

        // Industries
        'pl_om_ind_title'    => 'Varierte',
        'pl_om_ind_subtitle' => 'bransjer',
        'pl_om_ind_intro'    => 'Vi jobber i mange ulike bransjer, blant annet:',
        'pl_om_ind1'         => 'Lager og logistikk',
        'pl_om_ind2'         => 'Sport og fritid',
        'pl_om_ind3'         => 'Luftfart',
        'pl_om_ind4'         => 'Havn og marine',
        'pl_om_ind5'         => 'Fiskeindustri',
        'pl_om_ind6'         => 'Gjenvinning og miljø',

        // Certification
        'pl_om_cert_title'  => 'Miljøsertifisert bedrift',
        'pl_om_cert_text'   => 'Plamek er stolt Miljøfyrtårn-sertifisert, som bekrefter vårt engasjement for bærekraftig drift og miljøansvar.',
        'pl_om_cta_btn'     => 'Kontakt oss',

        /* ──────────── KONTAKT ──────────── */
        'pl_kt_hero_title1' => 'Kontakt',
        'pl_kt_hero_title2' => 'oss',
        'pl_kt_hero_desc'   => 'Ta kontakt for et uforpliktende tilbud på ditt neste monteringsprosjekt. Vi er klare til å hjelpe deg med profesjonelle løsninger.',
        'pl_kt_ci1_label'   => 'Telefon',
        'pl_kt_ci1_value'   => '+47 70 00 86 04',
        'pl_kt_ci1_note'    => 'Hverdager 07:00-16:00',
        'pl_kt_ci2_label'   => 'E-post',
        'pl_kt_ci2_value'   => 'post@plamek.no',
        'pl_kt_ci2_note'    => 'Svar innen 24 timer',
        'pl_kt_ci3_label'   => 'Adresse',
        'pl_kt_ci3_value'   => "Sundvollhovet\nN-3535 Krøderen",
        'pl_kt_ci4_label'   => 'Åpningstider',
        'pl_kt_ci4_value'   => "Man-Fre: 07:00-16:00\nLør-Søn: Stengt",
        'pl_kt_ceo_title'   => 'Snakk direkte med CEO',
        'pl_kt_ceo_name'    => 'Lars Erik Hoff',
        'pl_kt_ceo_role'    => 'CEO',
        'pl_kt_ceo_email'   => 'leh@plamek.no',
        'pl_kt_ceo_phone'   => '(+47) 40 41 15 44',
        'pl_kt_form_title'  => 'Send oss en forespørsel',
        'pl_kt_wh_title'    => 'Hva skjer videre?',
        'pl_kt_wh_l1'       => 'Vi tar kontakt innen 24 timer',
        'pl_kt_wh_l2'       => 'Gratis befaring og tilbud',
        'pl_kt_wh_l3'       => 'Detaljert prosjektplan',
        'pl_kt_loc_title'   => 'Finn oss',
        'pl_kt_loc_label'   => 'Besøksadresse',
        'pl_kt_loc_name'    => 'Plamek AS',
        'pl_kt_loc_street'  => 'Sundvollhovet',
        'pl_kt_loc_postal'  => 'N-3535 Krøderen',
        'pl_kt_loc_note'    => 'Vi anbefaler å avtale besøk på forhånd for å sikre at vi er tilgjengelige.',

        /* ──────────── SIMPLE HERO (referanser, nyheter) ──────────── */
        'pl_simple_hero_title1' => '',
        'pl_simple_hero_title2' => '',
        'pl_simple_hero_desc'   => '',
    ];

    return $map;
}

/* Lookup helper used by pl_meta() and pl_field() */
function pl_default(string $key, string $fallback = ''): string {
    $map = pl_defaults_map();
    return $map[$key] ?? $fallback;
}
